version: '3.8'

services:
  app:
    build:
      context: src
      dockerfile: dockerfile
    image: terraform_git_testing
    ports:
      - "8002:8002"
    restart: unless-stopped
    network_mode: host
