# Use an official Python runtime as a parent image
FROM python:3.10-slim-bookworm

# Set the working directory in the container
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y \
    build-essential libpoppler-cpp-dev \
    libmagickwand-dev \
    python3-distutils \
    poppler-utils \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*


# Copy the requirements file into the container at /usr/src/app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
ENV PYTHONPATH=/usr/src/app

# Copy the rest of your application code into the container
COPY . .

# Run the application
CMD ["python3", "run.py"]
